### ISSUE TITLE
Release a stable version

### ISSUE THREAD

**Issue by hkdobrev** [texthtml/silex-swiftmailer-profiler#1]
Hi! Do you think you could release a stable version so the package could be used with `minimum-stability` set to stable?

Also I think you can now require `silex/silex` with a stable version as well.

**Comment by mathroc** [comment]
I just made a release depending on stable version silex/silex and silex/web-profiler

thank you @hkdobrev for pointing this out

**Comment by hkdobrev** [comment]
Great! Thank you!
